apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort # ClusterIP, NodePort, LoadBalancer, Ingress
  ports:
    - port: 3000 # any internal pod in the kubernetes  cluster can access this pod labelled, component :web on port 3000
      targetPort: 3000 # exposed port on our container
      nodePort: 31515 # Port to be used from our device to access the container inside our kubernetes cluster 30000 - 32767
  selector:
      component: web